### ISSUE TITLE
Any idea for Pure Thermal 2 and FLIR Lepton 2.5?

### ISSUE THREAD

**Issue by rgm-22** [MartyMacGyver/UVCCamera#2]
Thank you for your contributions MartyMacGyver!

I have tried your code with Pure Themal 2 and FLIR Lepton 2.5 module and it doesn't work (no preview) :(

Any idea? I think that the firmware is similar and the resolution module is 160 x 120.

Here is the log:

V/USBMonitor: requestPermission:device=UsbDevice[mName=/dev/bus/usb/001/003,mVendorId=7758,mProductId=256,mClass=239,mSubclass=2,mProtocol=1,mManufacturerName=GroupGets,mProductName=PureThermal 1 v1.0.0,mVersion=2.00,mSerialNumberReader=android.hardware.usb.IUsbSerialReader$Stub$Proxy@a97c7b9,mConfigurations=[
    UsbConfiguration[mId=1,mName=null,mAttributes=128,mMaxPower=50,mInterfaces=[
    UsbInterface[mId=0,mAlternateSetting=0,mName=null,mClass=14,mSubclass=1,mProtocol=0,mEndpoints=[
    UsbEndpoint[mAddress=37,mAttributes=3,mMaxPacketSize=8,mInterval=9]]
    UsbInterface[mId=1,mAlternateSetting=1,mName=null,mClass=89,mSubclass=86,mProtocol=89,mEndpoints=[
    UsbEndpoint[mAddress=1,mAttributes=2,mMaxPacketSize=160,mInterval=120]]]]
V/USBMonitor: processConnect:
I/USBMonitor: UsbControlBlock:constructor
I/USBMonitor: UsbControlBlock:name=/dev/bus/usb/001/003, desc=68, rawDesc=[B@5539ac
V/MainActivity: onConnect:
V/UVCCameraTextureView: getPreviewTexture:
V/CameraThread: handleOpen:
    handleClose:
I/UVCCameraTextureView: RenderThread#updatePreviewSurface:
V/CameraThread: handleStopRecording:mMuxer=null
V/GLDrawer2D: initTex:
V/UVCCameraTextureView: getPreviewSurface:tex_id=1
I/MainActivity: supportedSize:null
V/CameraThread: handleStartPreview:
    handleClose:
    handleStopRecording:mMuxer=null
W/CameraThread: type=1400 audit(0.0:12920): avc: denied { create } for scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:r:untrusted_app_25:s0:c512,c768 tclass=netlink_kobject_uevent_socket permissive=0

**Comment by MartyMacGyver** [comment]
Yeah, I don't expect it to work. I use USBwebCameraPro which is what this code was forked from long ago. It seems to work better these days but try before you buy

**Comment by rgm-22** [comment]
I see. Thank you. Where is that code? This one https://github.com/saki4510t/UVCCamera?

**Comment by MartyMacGyver** [comment]
That was the code base for their app, but it's outdated and I'm not sure it's current (which is unfortunate).

Edit: looking at the issues tracker there, it seems the author is absent from recent conversations. Perhaps they've abandoned it...

**Comment by rgm-22** [comment]
I see :(

Yes, you are right. It looks like they've abandoned it :(
I'll continue researching.

Thank you!
